### ISSUE TITLE
Some more documentation on getting started would be helpful

### ISSUE THREAD

**Issue by mlewis-everley** [EddyVerbruggen/nativescript-ocr#3]
The docs show how to get started in nativescript but don't cover getting Tesseract installed for Android or iOS.

It would be really helpful (for newbs like me at least) to have maybe some links or a simple list of how we can get Tesseract installed, what dependencies this module requires etc.

For example, I am using Mint 18 with Tesseract installed from the package manager, but I am getting a "TypeError: Cannot read property 'tesseract' of undefined" error when trying to scan an image. I assume this is because the Tesseract libs are not installed for Android, but I am finding it quite hard to track down how to install this (most of the tutorials online invoilve using Eclipse, Android Studio etc etc).

Hope that makes some sense?

**Comment by mlewis-everley** [comment]
Just an update, in the end it appeared Tesseract was installed correctly, but running tns run didn't pull down all dependencies.

Running tns build however sorted the issue.

**Comment by codeyad** [comment]
@mlewis-everley can you please explain how can i set up this in a project?
