### ISSUE TITLE
actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file ../../ccutil/tessdatamanager.cpp, line 53

### ISSUE THREAD

**Issue by NathanWalker** [EddyVerbruggen/nativescript-ocr#5]
Curious if if you've ever seen this error while running from XCode - tessdata folder is properly referenced and everything.

> actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file ../../ccutil/tessdatamanager.cpp, line 53

<img width="754" alt="screen shot 2017-03-04 at 4 41 45 pm" src="https://cloud.githubusercontent.com/assets/457187/23583449/c8b631e4-00f9-11e7-9477-1fbe0f81070a.png">

**Comment by NathanWalker** [comment]
Shows the folder properly referenced...
<img width="248" alt="screen shot 2017-03-04 at 4 44 46 pm" src="https://cloud.githubusercontent.com/assets/457187/23583454/e67e6430-00f9-11e7-8742-ce800c0444f1.png">

**Comment by EddyVerbruggen** [comment]
Nope, how can I repro this?

**Comment by NathanWalker** [comment]
@EddyVerbruggen found it! this post answered it all 👍 
http://stackoverflow.com/questions/41131083/tesseract-traineddata-not-working-in-swift-3-0-project-using-version-4-0

**Comment by zhouhao27** [comment]
Don't quite understand. Why version 4.0 can only work with dat file 3.0.4?
