### ISSUE TITLE
Trouble getting retrieveText to accept arguments

### ISSUE THREAD

**Issue by davecoffin** [EddyVerbruggen/nativescript-ocr#7]
When I try to initialize the plugin, I get the following error: 
```
 Argument of type '{ image: ImageSource; }' is not assignable to parameter of type 'RetrieveTextOptions'.
  Types of property 'image' are incompatible.
    Type 'ImageSource' is not assignable to type 'string'.
```

Here's my code:

```
tryOcr() {

        ocr.retrieveText({
            image: imageSource.fromFile("~/ocrtest.png")
        }).then(result => {
            dialogs.alert({
                title: "Scan OK",
                message: result.text,
                okButtonText: "Sweet"
            });
        }); 
    }
```

**Comment by EddyVerbruggen** [comment]
How about continuing the discussion at #6?

**Comment by davecoffin** [comment]
Wow I am sorry, total random sequence of events, I saw your reply to this but thought it was to something else, then coincidentally started working on this again, went to issues to revisit the issue I created, didnt see it so I thought I actually never created it, so I created it again. 😲

**Comment by EddyVerbruggen** [comment]
Haha, figured something like that happened - happened to me before as well.

Note that I didn't have time to test the changes to 0.2.0 but since it was only a TypeScript fix I think it should work fine now.
