### ISSUE TITLE
tns run generates tesseract errors

### ISSUE THREAD

**Issue by mlewis-everley** [EddyVerbruggen/nativescript-ocr#8]
Hi,

I have been using this module for a little while with no issues. Today I had to remove plaforms and node_modules folder (as sometimes you have to) and after re-adding the platform, I can run `tns build ios` without issue.

However when I run `tns run ios` I get the following error before build:

`Expected "// !$*UTF8*$!" but "<" found`

I have upgraded the eng.traineddata file, which allows the app to run. But when I get to "reading" my image, the app quits with this message:

actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file ../../ccutil/tessdatamanager.cpp

My code is:

````
function scanImage()
{
    //console.log("Scanning image");

    var image = ImageSource.fromFile(temp_path);
    
    OCR
        .retrieveText({
            image: image
        }).then(
            function (result) {
                var text = result.text;

                // Move to our screen for reading
                FrameModule
                    .topmost()
                    .navigate({
                        context: {
                            OCRText: text
                        },
                        moduleName: 'views/read/read',
                        clearHistory: true
                    });
            },
            function (error) {
                Dialogs.alert({
                    title: "Error Reading Text",
                    message: error,
                    okButtonText: "OK"
                });
            }
        );
}
````

I am using nativescript 2.5.0 and nativescript-ocr 0.1.1.

As I said, this has only just started happening, last week I was using the OCR without issues and I haven't changed anything in my OCR code...

@EddyVerbruggen Have you got any ideas what might be going on?

Many thanks,

Mo

**Comment by EddyVerbruggen** [comment]
Dunno, perhaps you updated NativeScript as well? That `ImageSource.fromFile` is asynchronous AFAIK so maybe the image isn't fully read when parsed by the plugin? 🙃

**Comment by mlewis-everley** [comment]
OK, I have updated this module to 0.2.0 and also added the OCR call into a then:

````
import { ImageSource } from "image-source";
import * as OCR from "nativescript-ocr";
import * as Dialogs from "ui/dialogs";

var page;
var temp_path = global.temp_path;
var temp_thumb_path = global.temp_thumb_path;

function scanImage()
{
    console.log("Scanning image");
    let image = new ImageSource();

    image
        .fromFile(temp_path)
        .then(function(success) {
            if (success) {
                console.log("Opened image");
                OCR
                    .retrieveText({
                        image: image
                    }).then(
                        function (result) {
                            console.log("Read image");
                            var text = result.text;

                            FrameModule
                                .topmost()
                                .navigate({
                                    context: {
                                        OCRText: text
                                    },
                                    moduleName: 'views/read/read',
                                    clearHistory: true
                                });
                        },
                        function (error) {
                            Dialogs.alert({
                                title: "Error Reading Text",
                                message: error,
                                okButtonText: "OK"
                            });
                        }
                    );
            } else {
                Dialogs
                    .alert("Error reading image.")
                    .then(function () {
                    FrameModule
                        .topmost()
                        .navigate({
                        moduleName: 'views/camera/camera',
                        clearHistory: true
                    });
                });
            }
        });
}
````
I still get the same error.

I also did some digging and found this:

https://github.com/tesseract-ocr/tesseract/wiki/FAQ#actual_tessdata_num_entries_-tessdata_num_entrieserrorassert-failedin-file-ccutiltessdatamanagercpp-line-55_

Is the implication that I am using the wrong .traineddata? If so then which version should be used? Pods apparently downloaded 4.0.0 and I have used this data https://github.com/tesseract-ocr/tessdata/blob/4.00/eng.traineddata

:-s

**Comment by EddyVerbruggen** [comment]
That indeed is the wrong one. Just before your comment I did a massive update to the readme (and plugin) to point out the correct version. Please take a look and perhaps even clone the demo (included in this repo).

**Comment by mlewis-everley** [comment]
OK, so I reverted back to the old traineddata (that worked) and also found issue #5 and had a read.

Removed platform, deleted modules, made sure the tessdata folder was in the right place (I know that at least once I had placed it in the wrong location via xcode) and now it appears to work again.

Sometimes nativescript confuses me...

**Comment by EddyVerbruggen** [comment]
FYI with the latest version you no longer need to go into Xcode to tweak the folder (see the readme).

If problems come back and the demo app doesn't work either feel free to reopen.

**Comment by mlewis-everley** [comment]
OK, everything seems to be running as expected now, but I still have to link the tessdata folder in xcode.

Setting up the symlink as described in the docs causes this error:

`Expected "// !$*UTF8*$!" but "<" found`

To return when I run `tns run ios`.
